from algorithms.ac.ac import AC
from algorithms.pg.pg import PG
from algorithms.dqn.dqn import DQN
from algorithms.a3c.a3c import A3C
from algorithms.ddpg.ddpg import DDPG
from algorithms.td3.td3 import TD3
from algorithms.sac.sac import SAC
from algorithms.ppo.ppo import PPO
from algorithms.ppo_penalty.ppo_penalty import PPO_PENALTY
from algorithms.ppo_clip.ppo_clip import PPO_CLIP
from algorithms.dppo.dppo import DPPO
from algorithms.dppo_penalty.dppo_penalty import DPPO_PENALTY
from algorithms.dppo_clip.dppo_clip import DPPO_CLIP
from algorithms.trpo.trpo import TRPO
